# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQubeConnection'
    scannerMode: 'Other'
    organization: 'romanshchukintest'
    extraProperties: |
      sonar.projectKey=RomanShchukinTest_1
      sonar.projectName=RomanShchukinTest_1
- task: Maven@3.209.4
  inputs:
    mavenPomFile: '/home/vsts/work/1/s/sonarqube-scanner-maven/maven-multimodule/pom.xml'
    goals: 'clean verify -X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: JaCoCo
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
    codeCoverageClassFilter: '+:Module1'
#    jdkVersionOption: "1.11"
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'