# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - task: SonarQubePrepare@5
#  inputs:
#    SonarQube: 'SonarQubeConnection'
#    scannerMode: 'Other'
#    organization: 'romanshchukintest'
#    extraProperties: |
#      sonar.projectKey=RomanShchukinTest_1
#      sonar.projectName=RomanShchukinTest_1
- task: Maven@3.209.0
  inputs:
    mavenPomFile: '/home/vsts/work/1/s/sonarqube-scanner-maven/maven-multimodule/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    codeCoverageToolOption: Cobertura
#    sqMavenPluginVersionChoice: 'latest'
#    isJacocoCoverageReportXML: true
#    sonarQubeRunAnalysis: true

#- task: SonarQubePublish@5
#  inputs:
#    pollingTimeoutSec: '300'